export const UACTORS_FETCH_STARTED = "UACTOR_FETCH_STARTED";
export const UACTORS_FETCH_SUCCESS = "UACTOR_FETCH_SUCCESS";
export const UACTORS_FETCH_FAIL = "UACTOR_FETCH_FAIL";

export const UACTORS_REMOVE_STARTED = "UACTOR_REMOVE_STARTED";
export const UACTORS_REMOVE_SUCCESS = "UACTOR_REMOVE_SUCCESS";
export const UACTORS_REMOVE_FAIL = "UACTOR_REMOVE_FAIL";

export const UACTORS_CREATE_STARTED = "UACTOR_CREATE_STARTED";
export const UACTORS_CREATE_SUCCESS = "UACTOR_CREATE_SUCCESS";
export const UACTORS_CREATE_FAIL = "UACTOR_CREATE_FAIL";
